
package com.joseoliveros;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://joseoliveros.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param nombre
     * @return
     *     returns com.joseoliveros.Mensaje
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://joseoliveros.com/", className = "com.joseoliveros.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://joseoliveros.com/", className = "com.joseoliveros.SayHelloResponse")
    public Mensaje sayHello(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

}
